### login
POST http://localhost:3000/api/auth/42/login
Content-Type: application/json

{
	"login": "mbeaujar",
	"password": "123"
}

### try to access route without be log
GET http://localhost:3000/api/auth/42/protect