### login
POST http://localhost:3000/api/auth/42/login
Content-Type: application/json

{
	"username": "john",
	"password": "changeme"
}

### get the profile of the user login
GET http://localhost:3000/api/auth/42/profile