name: Prettier
on: [push]

jobs:
  build:
    name: Prettier
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: bahmutov/npm-install@v1
        with:
          working-directory: backend
      - uses: bahmutov/npm-install@v1
        with:
          working-directory: frontend

      - run: npm --prefix backend run format
      - run: npm --prefix frontend run format
      - run: git status
      - uses: mikeal/publish-to-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
